### ISSUE TITLE
"Give up" after Finishing issue in Trackmania

### ISSUE THREAD

**Issue by codecat** [maniaplanet/game-modes-mp3#8]
`TM2::IsWaiting()` returns false sometimes if the player retires after finishing a map. I can't find another way to detect retiring.

**Comment by codecat** [comment]
Even if I try to workaround this problem like this:

```
<manialink version="2">
    <script><!--
        while (True) {
            foreach (Event in PendingEvents) {
                if (Event.Type == CMlEvent::Type::KeyPress) {
                    if (Event.KeyCode == 29) {
                        declare Boolean BugFix_Retired for Players[0].User;
                        BugFix_Retired = True;
                    }
                }
            }
            yield;
        }
    --></script>
</manialink>
```

It doesn't trigger the event when the bug happens, but it triggers it any other time!

**Comment by Aessi** [comment]
What are you trying to achieve exactly? Do you want to know when the player presses the restart key or do you want to know when his status change (spawned/not spawned)?
On my side I enter a strange state if I press the restart key and cross the finish line at the exact same time. The camera switch to spectator mode and pressing the restart key doesn't have any effect until the outro sequence is finished and my car is respawned on its own. Is this similar to what you encounter?

**Comment by codecat** [comment]
Yes, that's exactly the problem I'm having. The workaround I tried above doesn't seem to work, either, (the event for the key press is never raised when the bug happens) so I'm not sure if this is a scripting thing or an engine input thing. This only happens in scripted modes, though.

**Comment by Aessi** [comment]
Could you try to replace the EndRace function in the TM2 library by [this one](https://gist.github.com/Aessi/9805f2ee61671954174e34d3185cb776) and tell me if it fixes the problem.

**Comment by codecat** [comment]
I'll be able to try this in a few hours.

**Comment by codecat** [comment]
Sorry for the delay!

This doesn't seem to fix it, sadly. :(

I took `TM2.Script.txt` from the dedicated server, placed it in:

```
Documents\ManiaPlanet\Scripts\Libs\Nadeo\TrackMania\TM2.Script.txt
```

Then I replaced the function (and put `WaitRace` above `EndRace` so that it can actually find the function when compiling), and it doesn't seem to change anything.

**Comment by codecat** [comment]
Oh, as an additional note, this happens both in multiplayer and solo gamemodes as well, so I'm not too certain this is a server to client issue. (It might be however, if solo mode still runs a local server? Not entirely sure.)

**Comment by Aessi** [comment]
It seems indeed that the problem is not only script related, so I'll have to report the problem to the engineers working on the engine. 
Could you describe the environment in which you run your test : maniaplanet local server or dedicated server, the game mode, if you are you using custom scripts, a server manager or anything that could alter the default behavior of the vanilla modes? Do you have a specific process to reproduce the bug more often? Any screenshot or video of what happens when the bug occurs?

**Comment by codecat** [comment]
Sure!

My current environment is running the game in a custom script in solo mode (title pack). However, this bug also happens on the scripted Time Attack gamemode. I'm particularly testing in Canyon, myself. You should be able to reproduce the problem in scripted time attack without any server controller.

I've uploaded a [quick video to YouTube](https://www.youtube.com/watch?v=SIYdLcAJ4to). (The bug happens in the first and third finish, but not in the second.) As you can see, I'm using the original game, in the original scripted modes, in the original maps, (even on a different computer than I normally use), so there is absolutely no custom scripts or anything running. (Besides maybe a custom car skin, but that's about it.)

The video shows it in a local in-game server, but it also happens in dedicated servers and solo mode.

**Comment by domino54** [comment]
A really quick overview says the mode event of type `CTmModeEvent::EType::Respawn` is just not sent after player cross the finish line. That's the entire problem why game doesn't respawn players that just finished a map.

**Comment by codecat** [comment]
Correction: It's _sometimes_ not after the player crosses the finish line _and the key/button is pressed_. Before the finish line it always works.

**Comment by Aessi** [comment]
@AngeloG : Thank you for all the informations. ;)

The respawn event is sent as long as the player is spawned, even after crossing the finish line. The outro camera capture the first press on the respawn button, but the second will respawn the player and send the event. If the player presses the respawn button and crosses the finish line at the same time, the events are not necessarily received in the right order inside the script. The respawn event can arrive a few milliseconds before the finish event, but the race is still considered finished and valid. That's what the fix proposed above tried to fix, but apparently it was not enough.

**Comment by codecat** [comment]
@Aessi: Are you sure the event is received at all? I'm having trouble catching the events in my own loop checking `PendingEvents`.

**Comment by codecat** [comment]
Also, if you look at the video, in the first finish I press delete about a second after I finish, so I'm not sure this theory has any solid ground:

> the player presses the respawn button and crosses the finish line at the same time

**Comment by Aessi** [comment]
Then maybe there is a misunderstanding on what the bug is.

On my side I was able to reproduce a bug where crossing the finish line and pressing the respawn button approximately at the same time caused the player to be locked in the outro state. When it happened I could pressed the restart button as much as I wanted and the car was not restarting. I had to wait for the whole outro sequence to be finished before my car was automatically respawned by the script. That's what the modification proposed above fixed.

In your video you only press the respawn button once and it stops the camera animation but do not respawn? Then you do not press the button a second time to restart the race immediately?

The intended behavior, probably not the best one, if everything was working properly is the following : 
- I cross the finish line
- I press the respawn button
- the outro camera stop but the outro sequence continue
- I press the respawn button a second time
- the outro sequence stop and my car is respawned on the start line

In this case the bug in your video would be at your second run where the car is respawned immediately on the first button press. But this is the behavior you want. You expect that whenever you press the respawn button after crossing the finish line, your car is respawned at the start line immediately.
Is this correct?

**Comment by codecat** [comment]
Yes, immediately respawning is the behavior that you can see in the legacy
game modes, so that would be the expected behavior.

**Comment by Aessi** [comment]
Okay. In this case the problem is already known and it's in the list of things to improve. For the time being I don't have any ETA for a possible solution.

**Comment by codecat** [comment]
Sounds good, looking forward for a fix. Thanks!

**Comment by codecat** [comment]
This is fixed with MP4, so we can close this now 😍
